# ./themes/argonaut.toml
[font]
size = 16

[font.bold]
family = "Inconsolata LGC Nerd Font"
style = "Bold"

[font.italic]
family = "Inconsolata LGC Nerd Font"
style = "Italic"

[font.normal]
family = "Inconsolata LGC Nerd Font"
style = "Regular"

[window]
decorations = "Buttonless"

[window.dimensions]
columns = 85
lines = 35

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
  { key = "Escape", mods = "Control",action = "ToggleViMode"   },
  { key = "I", mode = "Vi|~Search", action = "ToggleViMode"   },
]

[general]
import = [
        "~/.config/alacritty/themes/citylights.toml", ]
