# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"


# : Status {{{

[status]
separator_open  = ""
separator_close = ""

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "blue", bg = "black" }
progress_error  = { fg = "red", bg = "black" }

# Permissions
perm_sep   = { fg = "darkgray" }
perm_type  = { fg = "green" }
perm_read  = { fg = "yellow" }
perm_write = { fg = "red" }
perm_exec  = { fg = "cyan" }

# : }}}

# : Mode {{{

[mode]

normal_main = { fg = "#3b3836", bg = "blue", bold = true }
normal_alt  = { fg = "blue", bg = "#3b3836"}

# Select mode
select_main = { bg = "red", bold = true }
select_alt  = { fg = "red", bg = "#3b3836"}

# Unset mode
unset_main = { bg = "red", bold = true }
unset_alt  = { fg = "red", bg = "#3b3836"}

# : }}}
