# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio = [ 1, 2, 3 ]
sort_dir_first = true
show_hidden = true

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"

[git]
repo_prefix = true
status_cache = true

[preview]
max_width = 900
max_height = 1000

[opener]
open = [
  { run = 'open "$1"', desc = "Open", for = "unix" },
]
edit = [
  { run = '${EDITOR:-vi} "$@"', desc = "$EDITOR", block = true, for = "unix" },
]

[open]
rules = [
  # PDF
  { name = "*.pdf", use = "open" },
]
