autocmd!
syntax on
set secure
set hidden
set number
set mouse=a
set mousehide
" Terminal
set t_Co=256
set termencoding=utf-8
set encoding=utf-8
set fileencodings=utf8,cp1251
" Disable sound
set noerrorbells
set novisualbell

" Удобное поведение backspace
set backspace=indent,eol,start
set scrolloff=7

" черточки на табах
set listchars=tab:>-,trail:-
set list

" Tab панель вверху отображается всегда
set showtabline=2

" Настройки табов
set tabstop=4           " Number of spaces that a tab counts for
set shiftwidth=4        " Number of spaces to use for autoindent
set softtabstop=4       " Enables backspace over 4 spaces
set smarttab
set expandtab           " use space for tabs
set autoindent
set textwidth=79        " Set maximum width of text (not code)
set nowrap

" Вырубаем .swp и ~ (резервные) файлы
set nobackup
set noswapfile

" Yank to system clipboard
set clipboard=unnamed

" Настройка поиска
set ignorecase
set smartcase
set hlsearch
set incsearch


set background=dark
" kanagawa-dragon kanagawa-wave kanagawa-lotos
" colorscheme kanagawa-wave


""" Mapping
let mapleader = ","

" Check spell
map <leader>ss :setlocal spell!<CR>

nmap <C-o> :back
nmap <C-i> :forward

" Ctrl-C Ctrl-V
inoremap <C-v> <ESC>"+pa
vnoremap <C-c> "+y
vnoremap <C-d> "+d


" Other
command! W execute 'w !sudo tee % > /dev/null' <bar> edit! " переоткрыть с sudo и сохранить
