autocmd!
syntax on
set secure
set hidden
set number
set mouse=a
set mousehide
" Terminal
set t_Co=256
set termencoding=utf-8
set encoding=utf-8
set fileencodings=utf8,cp1251
" Disable sound
set noerrorbells
set novisualbell

" Удобное поведение backspace
set backspace=indent,eol,start
set scrolloff=7

" черточки на табах
set listchars=tab:>-,trail:-
set list

" Tab панель вверху отображается всегда
set showtabline=2

" Настройки табов
set tabstop=4           " Number of spaces that a tab counts for
set shiftwidth=4        " Number of spaces to use for autoindent
set softtabstop=4       " Enables backspace over 4 spaces
set smarttab
set expandtab           " use space for tabs
" set textwidth=79        " Set maximum width of text (not code)
set nowrap

" Вырубаем .swp и ~ (резервные) файлы
set nobackup
set noswapfile

" Yank to system clipboard
set clipboard=unnamed

" Настройка поиска
set ignorecase
set smartcase
set hlsearch
set incsearch

set background=dark
" kanagawa-dragon kanagawa-wave kanagawa-lotos
" colorscheme kanagawa-wave

" Check spell
map <leader>ss :setlocal spell!<CR>

nmap <C-o> :back
nmap <C-i> :forward

" Ctrl-C Ctrl-V
inoremap <C-v> <ESC>"+pa
vnoremap <C-c> "+y
vnoremap <C-d> "+d

" Other
command! W execute 'w !sudo tee % > /dev/null' <bar> edit! " переоткрыть с sudo и сохранить

""" Mapping
let mapleader = " "
imap jj <Esc>
map й q
map ц w
map у e
map к r
map е t
map н y
map г u
map ш i
map щ o
map з p
map х [
map ъ ]
map ф a
map ы s
map в d
map а f
map п g
map р h
map о j
map л k
map д l
map ж ;
map э '
map ё \
map я z
map ч x
map с c
map м v
map и b
map т n
map ь m
map б ,
map ю .
map Й Q
map Ц W
map У E
map К R
map Е T
map Н Y
map Г U
map Ш I
map Щ O
map З P
map Х {
map Ъ }
map Ф A
map Ы S
map В D
map А F
map П G
map Р H
map О J
map Л K
map Д L
map Ж :
map Э "
map Я Z
map Ч X
map С C
map М V
map И B
map Т N
map Ь M
map Б <
map Ю >
map Ё /|
