# If not running interactively, don't do anything
[[ $- != *i* ]] && return

export ZSH="$HOME/.oh-my-zsh"
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
#ZSH_THEME="chepi"
#plugins=( git time )
source $ZSH/oh-my-zsh.sh

# General
# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nvim'
  export VISUAL='nvim'
else
  export EDITOR='nvim'
  export VISUAL='nvim'
fi

# set vi mode
set -o vi

# Aliases
source $HOME/dotfiles/aliases.sh

# PROMPT Starship https://starship.rs/guide/
eval "$(starship init zsh)"
