# If not running interactively, don't do anything
[[ $- != *i* ]] && return
export ZSH="$HOME/.oh-my-zsh"
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
#ZSH_THEME="dst"
##ZSH_THEME="mh"
#ZSH_THEME="mlh"
#ZSH_THEME="headline"
#ZSH_THEME="murilasso"

# themes=("bira" "dst" "mlh" "headline" "murilasso")
# random_index=$((RANDOM % ${#themes[@]}))
# ZSH_THEME=${themes[$random_index]}
#export ZSH_THEME
# echo "Theme: $ZSH_THEME"
ZSH_THEME="mlh"


plugins=(git)

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

# set vi mode
set -o vi

# Aliases
alias home="$EDITOR ~/.oh-my-zsh"
alias config="$EDITOR ~/.config"
alias tf="terraform"

alias note="$EDITOR ~/notes/."

## k8s
alias k="kubectl"
alias kgp="kubectl get pods"
