# If not running interactively, don't do anything
[[ $- != *i* ]] && return

export ZSH="$HOME/.oh-my-zsh"
ZSH_CUSTOM="$HOME/dotfiles/zsh"
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="mch"
plugins=(git)
ZSH_COMPDUMP=~/.zcompdump
source $ZSH/oh-my-zsh.sh

# General
export EDITOR='nvim'
export VISUAL='nvim'
export VAULT_HOME="$HOME/Volumes/mch"

# Additional PATH
if [[ -d "$HOME/dotfiles/scripts" ]]; then
  path=("$HOME/dotfiles/scripts" $path)
fi
# bun global packages (qmd, etc.)
if [[ -d "$HOME/.bun/bin" ]]; then
  path=("$HOME/.bun/bin" $path)
fi

# set vi mode
set -o vi

# Aliases
source $HOME/dotfiles/aliases.sh

# nnn file manager (plugins via ;key, preview-tui needs tmux)
export NNN_FIFO='/tmp/nnn.fifo'
export NNN_PLUG='p:preview-tui;g:gitstatus;o:fzopen;d:dragdrop'
export NNN_BMS='p:~/projects;d:~/dotfiles;h:~'
export NNN_FCOLORS='c1e2272e006033f7c6d6abc4'
export NNN_BATTHEME='ansi'
export NNN_PAGER='less -R'

# Completions (fpath must be before compinit, oh-my-zsh already calls compinit)
fpath+=~/.zfunc

[ -f "$HOME/.local_env.zsh" ] && source "$HOME/.local_env.zsh"
